Don't translate rrs gene
This is not a protein coding gene, so it should not be translated.

Translating it currently comes with a warning

    Gene length of 'rrs' is not a multiple of 3. will pad with N

which will soon be changed to an error¹

    ERROR: Reference file 'config/Mtb_H37Rv_NCBI_Annot.gff' has errors:
        'rrs' has length 1537 which is not a multiple of 3.

¹ https://github.com/nextstrain/augur/issues/1895